services:

  - type: web
    name: smartpayplug-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js

  - type: web
    name: smartpayplug-frontend
    env: static
    buildCommand: echo build
    staticPublishPath: .
